"""Offline HocusScript parsing, validation, and formatting."""

from .bundle import (
    BUNDLE_VERSION, MODULE_BUNDLE_VERSION, BundleValidationError, CompiledBundle,
    decode_compiled_bundle,
)
from .catalog import (
    CATALOG_SCHEMA_URI,
    CATALOG_VERSION,
    CatalogProvider,
    CatalogSnapshot,
    CatalogValidationError,
    FakeCatalogProvider,
    SnapshotCatalogProvider,
    decode_catalog_snapshot,
)
from .compiler import SUPPORTED_LANGUAGE_VERSIONS, compile_source, validate_graph
from .diagnostics import Diagnostic, SourcePosition, SourceSpan
from .document_lowering import (
    DOCUMENT_SCHEMA_URI,
    PREVIEW_VERSION,
    DocumentLoweringError,
    DocumentPreview,
    lower_bundle_to_document,
)
from .editor import (
    CompletionItem,
    CompletionResult,
    EditorCheckResult,
    EditorFormatResult,
    check_source,
    complete_source,
    format_source,
)
from .formatter import format_graph
from .exporter import ExportDiagnostic, NetworkDocumentExport, export_network_document
from .model import (
    COMPILER_VERSION,
    EXPANSION_MAP_VERSION,
    GRAPH_SPEC_VERSION,
    MODULE_COMPILER_VERSION,
    MODULE_GRAPH_SPEC_VERSION,
    MODULE_LANGUAGE_VERSION,
    CompileResult,
    ExpansionFrame,
    ExpansionMap,
    ExpansionOrigin,
    ExpansionStack,
    GraphSpec,
    ModuleDependency,
    RelatedOrigin,
    graph_spec_from_dict,
)
from .modules import MODULE_MANIFEST_SCHEMA_URI, ModuleManifest, decode_module_manifest
from .project import (
    ExternalLibraryAlias,
    LockVerificationResult,
    ModuleLockRecord,
    ProjectContext,
    ProjectError,
    compile_path,
    update_project_lock,
    verify_project_lock,
)
from .semantic import (
    CatalogConstraint,
    ConnectionSelection,
    DeferredCheck,
    ExternalNodeBinding,
    OperatorSelection,
    ParameterSelection,
    SemanticResult,
    resolve_graph,
)

__all__ = [
    "BUNDLE_VERSION",
    "MODULE_BUNDLE_VERSION",
    "BundleValidationError",
    "CATALOG_SCHEMA_URI",
    "CATALOG_VERSION",
    "CatalogProvider",
    "CatalogSnapshot",
    "CatalogValidationError",
    "CompileResult",
    "CompletionItem",
    "CompletionResult",
    "COMPILER_VERSION",
    "MODULE_COMPILER_VERSION",
    "MODULE_GRAPH_SPEC_VERSION",
    "MODULE_LANGUAGE_VERSION",
    "EXPANSION_MAP_VERSION",
    "CompiledBundle",
    "CatalogConstraint",
    "ConnectionSelection",
    "DeferredCheck",
    "Diagnostic",
    "DOCUMENT_SCHEMA_URI",
    "DocumentLoweringError",
    "DocumentPreview",
    "EditorCheckResult",
    "EditorFormatResult",
    "ExportDiagnostic",
    "ExpansionFrame",
    "ExpansionMap",
    "ExpansionOrigin",
    "ExpansionStack",
    "FakeCatalogProvider",
    "GraphSpec",
    "GRAPH_SPEC_VERSION",
    "ProjectContext",
    "ProjectError",
    "PREVIEW_VERSION",
    "NetworkDocumentExport",
    "ModuleDependency",
    "RelatedOrigin",
    "SUPPORTED_LANGUAGE_VERSIONS",
    "SourcePosition",
    "SourceSpan",
    "ExternalNodeBinding",
    "ExternalLibraryAlias",
    "LockVerificationResult",
    "ModuleLockRecord",
    "ModuleManifest",
    "MODULE_MANIFEST_SCHEMA_URI",
    "OperatorSelection",
    "ParameterSelection",
    "SemanticResult",
    "SnapshotCatalogProvider",
    "compile_path",
    "compile_source",
    "check_source",
    "complete_source",
    "decode_compiled_bundle",
    "decode_catalog_snapshot",
    "decode_module_manifest",
    "format_graph",
    "format_source",
    "export_network_document",
    "graph_spec_from_dict",
    "lower_bundle_to_document",
    "resolve_graph",
    "validate_graph",
    "update_project_lock",
    "verify_project_lock",
]
