"""Offline HocusScript parsing, validation, and formatting."""

from .bundle import (
    BUNDLE_VERSION, MODULE_BUNDLE_VERSION, BundleValidationError, CompiledBundle,
    decode_compiled_bundle,
)
from .catalog import (
    CATALOG_SCHEMA_URI,
    CATALOG_VERSION,
    CatalogProvider,
    CatalogSnapshot,
    CatalogValidationError,
    FakeCatalogProvider,
    SnapshotCatalogProvider,
    decode_catalog_snapshot,
)
from .compiler import SUPPORTED_LANGUAGE_VERSIONS, compile_source, validate_graph
from .diagnostics import Diagnostic, SourcePosition, SourceSpan
from .document_lowering import (
    DOCUMENT_SCHEMA_URI,
    PREVIEW_VERSION,
    DocumentLoweringError,
    DocumentPreview,
    lower_bundle_to_document,
)
from .editor import (
    CompletionItem,
    CompletionResult,
    EditorCheckResult,
    EditorFormatResult,
    check_source,
    complete_source,
    format_source,
)
from .expander import (
    ExpansionLimits,
    ModuleExpansionError,
    ResolvedModuleUnit,
    expand_module_graph,
    expand_resolved_module_dag,
    resolved_import_map,
    resolved_units_from_dag,
    validate_module_interfaces,
)
from .formatter import format_graph, format_syntax
from .lock_update import update_project_module_lock
from .lock_update_result import ModuleLockUpdateEntry, ModuleLockUpdateResult
from .exporter import ExportDiagnostic, NetworkDocumentExport, export_network_document
from .external_roots import (
    EXTERNAL_ROOTS_INSPECTION_KIND,
    EXTERNAL_ROOTS_INSPECTION_SCHEMA_URI,
    ExternalLibraryRootPin,
    ExternalModuleRootsInspection,
    inspect_external_module_roots,
)
from .model import (
    COMPILER_VERSION,
    EXPANSION_MAP_VERSION,
    GRAPH_SPEC_VERSION,
    MODULE_COMPILER_VERSION,
    MODULE_GRAPH_SPEC_VERSION,
    MODULE_LANGUAGE_VERSION,
    CompileResult,
    ExpansionFrame,
    ExpansionMap,
    ExpansionOrigin,
    ExpansionStack,
    GraphSpec,
    ModuleDependency,
    RelatedOrigin,
    graph_spec_from_dict,
)
from .module_compiler import (
    FormattedModuleSource,
    ModuleProjectCompileError,
    ModuleProjectCompileResult,
    compile_project_mixed_module_graph,
    compile_project_module_graph,
)
from .module_format import (
    ModuleProjectFormatError,
    ModuleProjectFormatResult,
    format_project_module_path,
)
from .module_lock_plan import plan_project_module_lock
from .module_lock_plan_result import (
    MODULE_LOCK_PLAN_KIND,
    MODULE_LOCK_PLAN_SCHEMA_URI,
    ModuleLockPlanResult,
)
from .mixed_lock_update import update_project_mixed_module_lock
from .mixed_lock_update_result import (
    MIXED_MODULE_LOCK_UPDATE_KIND,
    MIXED_MODULE_LOCK_UPDATE_SCHEMA_URI,
    MixedModuleLockUpdateResult,
)
from .mixed_project_editor import (
    complete_mixed_path,
    complete_mixed_project_source,
    definition_mixed_path,
    definition_mixed_project_source,
)
from .module_semantic import (
    ModuleSemanticCompileError,
    ModuleSemanticCompileResult,
    compile_project_mixed_module_bundle,
    compile_project_mixed_module_semantic,
    compile_project_module_bundle,
    compile_project_module_semantic,
)
from .modules import MODULE_MANIFEST_SCHEMA_URI, ModuleManifest, decode_module_manifest
from .project import (
    ExternalLibraryAlias,
    LockVerificationResult,
    ModuleLockRecord,
    ProjectContext,
    ProjectError,
    compile_path,
    update_project_lock,
    verify_project_lock,
)
from .project_editor import (
    ProjectCompletionItem,
    ProjectCompletionResult,
    ProjectDefinitionItem,
    ProjectDefinitionResult,
    ProjectEditorPins,
    complete_path,
    complete_project_source,
    definition_path,
    definition_project_source,
)
from .parser import parse_syntax
from .resolved_modules import (
    ModuleResolutionError,
    ModuleSourceEnvelope,
    ResolvedImport,
    ResolvedModuleDag,
    ResolvedModuleLimits,
    ResolvedModuleRecord,
    canonical_module_uri,
    module_interface_digest,
    module_source_digest,
    module_transitive_digest,
    validate_resolved_module_dag,
)
from .resolver import resolve_project_module_dag
from .semantic import (
    CatalogConstraint,
    ConnectionSelection,
    DeferredCheck,
    ExternalNodeBinding,
    OperatorSelection,
    ParameterSelection,
    SemanticResult,
    resolve_graph,
)
from .syntax import (
    ExportStmt,
    ImportDecl,
    ModuleDecl,
    ModuleExportDecl,
    ModuleParamDecl,
    NamedArgument,
    ParamRefExpr,
    SymbolRefExpr,
    SyntaxSource,
    UseDecl,
)

__all__ = [
    "BUNDLE_VERSION",
    "MODULE_BUNDLE_VERSION",
    "BundleValidationError",
    "CATALOG_SCHEMA_URI",
    "CATALOG_VERSION",
    "CatalogProvider",
    "CatalogSnapshot",
    "CatalogValidationError",
    "CompileResult",
    "CompletionItem",
    "CompletionResult",
    "COMPILER_VERSION",
    "MODULE_COMPILER_VERSION",
    "MODULE_GRAPH_SPEC_VERSION",
    "MODULE_LANGUAGE_VERSION",
    "EXPANSION_MAP_VERSION",
    "CompiledBundle",
    "CatalogConstraint",
    "ConnectionSelection",
    "DeferredCheck",
    "Diagnostic",
    "DOCUMENT_SCHEMA_URI",
    "DocumentLoweringError",
    "DocumentPreview",
    "EditorCheckResult",
    "EditorFormatResult",
    "ExportDiagnostic",
    "EXTERNAL_ROOTS_INSPECTION_KIND",
    "EXTERNAL_ROOTS_INSPECTION_SCHEMA_URI",
    "ExternalLibraryRootPin",
    "ExternalModuleRootsInspection",
    "ExpansionFrame",
    "ExpansionMap",
    "ExpansionOrigin",
    "ExpansionStack",
    "ExpansionLimits",
    "FormattedModuleSource",
    "FakeCatalogProvider",
    "GraphSpec",
    "GRAPH_SPEC_VERSION",
    "ProjectContext",
    "ProjectError",
    "ProjectEditorPins",
    "ProjectCompletionItem",
    "ProjectCompletionResult",
    "ProjectDefinitionItem",
    "ProjectDefinitionResult",
    "PREVIEW_VERSION",
    "NetworkDocumentExport",
    "ModuleDependency",
    "ModuleExpansionError",
    "ModuleProjectCompileError",
    "ModuleProjectCompileResult",
    "ModuleProjectFormatError",
    "ModuleProjectFormatResult",
    "ModuleSemanticCompileError",
    "ModuleSemanticCompileResult",
    "RelatedOrigin",
    "SUPPORTED_LANGUAGE_VERSIONS",
    "SourcePosition",
    "SourceSpan",
    "ExternalNodeBinding",
    "ExternalLibraryAlias",
    "LockVerificationResult",
    "ModuleLockRecord",
    "ModuleLockUpdateEntry",
    "ModuleLockUpdateResult",
    "MODULE_LOCK_PLAN_KIND",
    "MODULE_LOCK_PLAN_SCHEMA_URI",
    "ModuleLockPlanResult",
    "MIXED_MODULE_LOCK_UPDATE_KIND",
    "MIXED_MODULE_LOCK_UPDATE_SCHEMA_URI",
    "MixedModuleLockUpdateResult",
    "ModuleManifest",
    "ModuleResolutionError",
    "ModuleSourceEnvelope",
    "MODULE_MANIFEST_SCHEMA_URI",
    "OperatorSelection",
    "ParameterSelection",
    "SemanticResult",
    "ResolvedImport",
    "ResolvedModuleDag",
    "ResolvedModuleLimits",
    "ResolvedModuleRecord",
    "ResolvedModuleUnit",
    "SnapshotCatalogProvider",
    "compile_path",
    "compile_project_mixed_module_graph",
    "compile_project_mixed_module_bundle",
    "compile_project_mixed_module_semantic",
    "compile_project_module_graph",
    "compile_project_module_bundle",
    "compile_project_module_semantic",
    "canonical_module_uri",
    "compile_source",
    "check_source",
    "complete_source",
    "complete_mixed_path",
    "complete_mixed_project_source",
    "complete_path",
    "complete_project_source",
    "decode_compiled_bundle",
    "decode_catalog_snapshot",
    "decode_module_manifest",
    "definition_path",
    "definition_mixed_path",
    "definition_mixed_project_source",
    "definition_project_source",
    "format_graph",
    "format_source",
    "format_project_module_path",
    "export_network_document",
    "inspect_external_module_roots",
    "expand_module_graph",
    "expand_resolved_module_dag",
    "graph_spec_from_dict",
    "lower_bundle_to_document",
    "module_interface_digest",
    "module_source_digest",
    "module_transitive_digest",
    "plan_project_module_lock",
    "resolve_graph",
    "resolve_project_module_dag",
    "resolved_import_map",
    "resolved_units_from_dag",
    "validate_graph",
    "validate_module_interfaces",
    "validate_resolved_module_dag",
    "update_project_lock",
    "update_project_mixed_module_lock",
    "update_project_module_lock",
    "verify_project_lock",
    "ExportStmt",
    "ImportDecl",
    "ModuleDecl",
    "ModuleExportDecl",
    "ModuleParamDecl",
    "NamedArgument",
    "ParamRefExpr",
    "SymbolRefExpr",
    "SyntaxSource",
    "UseDecl",
    "format_syntax",
    "parse_syntax",
]
